[build]
target = "thumbv7em-none-eabihf"
#target-dir = "target/stm32f4-drone"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]
runner = "probe-rs run --chip STM32F411CEUx"
