[package]
name = "stm32"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
cortex-m = "0.7.7"
panic-halt = "1.0.0"

embedded-hal = "1.0"
nb = "1"
stm32f1xx-hal = {version = "0.11.0", features=["stm32f103", "medium"]}

[dev-dependencies]

