[build]
target = "thumbv7m-none-eabi"
#target-dir = "target/stm32f1-controller"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8"
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

